### ISSUE TITLE
Замечания от Кирилла

### ISSUE THREAD

**Issue by lisa-bella97** [go-park-mail-ru/2019_2_Pirogi#10]
- [x] добавить возможность писать в конфиг единицы измерения, например, '10s' или '100500h'
- [x] заменить InsertOrUpdate на Upsert
- [x] все коды статуса (401 и др.) заменить на встроенные константы пакета http

**Comment by SmartPhoneJava** [comment]
По поводу формата time.Duration в json советую посмотреть хорошее решение - https://stackoverflow.com/a/48051946
